services:
  # Backend API
  - type: web
    name: ai-stock-analyzer-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  # Frontend
  - type: web
    name: ai-stock-analyzer-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-stock-analyzer-backend.onrender.com 